name: Build and Zip Chrome & Firefox Extension

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"

      - name: Install dependencies
        run: yarn

      - name: Build Chrome
        run: yarn build:chrome

      - name: Upload Chrome extension artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vite-web-extension-chrome
          path: dist_chrome

      - name: Build Firefox
        run: yarn build:firefox

      - name: Upload Firefox extension artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vite-web-extension-firefox
          path: dist_firefox
